name = "abeai-api-worker"
main = "index.js"
compatibility_date = "2024-03-29"

kv_namespaces = [
  { binding = "ABEAI_KV", id = "5084daa8615147bab2771668a729620d" }
]

# Remove "workers_logs" and "no_bundle"
# We no longer need to set the build or workers logs like this.

[build]
command = "echo 'No build needed'"
upload.format = "modules"

[vars]
FORCE_MONETIZATION = "true"

# Remove the triggers section with routes
# You don't need routes here; we're managing the proxy via the gateway worker.
