name = "abeai-api-worker"
main = "index.js"
compatibility_date = "2024-03-29"

kv_namespaces = [
  { binding = "ABEAI_KV", id = "5084daa8615147bab2771668a729620d" }
]

# Enable logging with Cloudflare Workers for better observability and debugging
[build]
no_bundle = true

[vars]
FORCE_MONETIZATION = "true"

[triggers]
routes = ["api.abeai.health/*"]  # Or any specific route you want to configure

# Enable Worker observability
[workers_logs]
enabled = true
